"""
realword.py — detect correctly spelled words used in the wrong place.

The spellchecker is blind to these by construction. `check_sentence()`
examines each token independently and skips anything the confidence gate
accepts, so a real Khasi word sitting where a different real Khasi word
belongs passes silently. Kukich (1992) puts real-word errors at a quarter
to a half of all errors in human writing, so this is not a corner case.

Approach — Mays, Damerau and Mercer (1991), with a word trigram model
(khasi_spell.ngram, Stupid Backoff over the corpus):

  1. Consider only tokens the lexicon records. Anything else is an ordinary
     spelling error and belongs to the existing path.
  2. Build a confusion set: lexicon words one edit away from the token,
     generated by edit-then-lookup rather than a vocabulary scan.
  3. Score how well the token and each alternative fit the slot, using the
     three trigrams that contain it, within the same sentence — in the
     corpus's spelling (no ï, ñ or apostrophe), the only one the model has
     seen. An alternative that differs only by a diacritic or an apostrophe
     is the same word and is never proposed.
  4. Flag the best alternative when it fits better by at least `min_margin`
     log units.

The n-gram model already encodes commonness, so no separate frequency rule
is applied by default (`freq_ratio=0`). There used to be one hidden in a
default of 1.0 — "no constraint" according to the docstring — which in fact
required every alternative to be at least as frequent as the typed word.
`ka` is the commonest word in the corpus, so `ka` could never be flagged, in
any sentence, whatever the context said.

An embedding scorer (`scorer="embedding"`, cosine to the context centroid)
is kept so the original comparison stays reproducible. It measured far
worse: at an identical 0.7% false-positive rate it found 3.8% of errors
against the n-gram scorer's 33.8%, because cosine-to-centroid asks "is this
word roughly on topic" when the question is "does it belong in this slot".
It needs a frequency floor to avoid proposing rare words, so pass
`freq_ratio` (for example 2.0) when using it.

Measurement
-----------
`scripts/eval_realword.py` reproduces the protocol: untouched corpus
sentences for false positives, sentences with one word swapped for a
lexicon neighbour for recall, and ka/ki swaps for the clitic case, each at a
range of margins. The README section "Real-word error detection" carries
the current table. Defaults sit at the precision end: wrongly "correcting"
a word the writer got right costs more trust than a missed error is worth.
"""
from __future__ import annotations

import math
from collections import OrderedDict
from dataclasses import dataclass, asdict, field
from typing import Any, Iterable, Optional

from khasi_engine import tokens as _tokens

# Khasi orthographic inventory for single-character edits. c, f, q, v, x and
# z are excluded — they do not occur in native Khasi words.
_ALPHABET = "abdeghijklmnoprstuwy" + "ïñ" + "áéíóúý"

# The tokenisation every component shares, so offsets agree with /check.
_TOKEN = _tokens.WORD_PATTERN

# Upper bound on each cache; the detector lives as long as the service.
_CACHE_LIMIT = 20000


@dataclass
class RealWordFlag:
    """A correctly spelled word that may be the wrong word."""

    word: str
    suggestion: str
    start: int
    end: int
    margin: float                    # how much better the alternative fits
    word_fit: float
    suggestion_fit: float
    word_freq: int
    suggestion_freq: int
    alternatives: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class RealWordDetector:
    """
    Contextual detector for real-word errors.

    Parameters
    ----------
    speller :
        A loaded `KhasiSpeller`. Its lexicon supplies the confusion sets and
        its corpus frequencies the commonness prior.
    min_margin :
        How much better an alternative must fit the context before anything
        is flagged. Log units for the n-gram scorer, cosine points for the
        embedding one. Higher is more conservative. Can be overridden per
        call with `check(text, min_margin=...)`.
    freq_ratio :
        When above 0, the alternative must be at least this many times
        commoner in the corpus than the observed word. 0 (the default) is no
        constraint, which is right for the n-gram scorer: it already
        accounts for commonness. The embedding scorer needs a value such as
        2.0 to keep it from proposing rare words near the context vector.
        Alternatives the corpus never attests are always skipped.
    scorer :
        "ngram" (default) or "embedding". See the measurements above.
    min_context :
        Minimum number of usable context words. Below this there is not
        enough signal and the token is skipped.
    """

    def __init__(
        self,
        speller: Any,
        min_margin: float = 8.0,    # log units; see scripts/eval_realword.py
        freq_ratio: float = 0.0,    # the LM already encodes commonness
        min_context: int = 2,
        window: int = 6,
        max_alternatives: int = 12,
        min_length: int = 2,
        scorer: str = "ngram",      # "ngram" | "embedding"
    ) -> None:
        self.sp = speller
        self.scorer = scorer
        self._lm = None
        self.min_margin = min_margin
        self.freq_ratio = freq_ratio
        self.min_context = min_context
        self.window = window
        self.max_alternatives = max_alternatives
        self.min_length = min_length
        self._model = None
        self._freq: dict[str, int] = {}
        self._vec: "OrderedDict[str, Any]" = OrderedDict()   # word -> unit vector
        self._conf: "OrderedDict[str, list]" = OrderedDict() # word -> confusion set

    # ------------------------------------------------------------------
    # Lazy resources
    # ------------------------------------------------------------------

    def _ensure(self) -> None:
        if self.scorer == "ngram":
            if self._lm is None:
                # The speller's own model — one instance shared with context
                # re-ranking. This used to build a second copy, so a service
                # that ran both held two ~170 MB models.
                self._lm = self.sp._lm()
                if self._lm is None:
                    raise FileNotFoundError(
                        "no n-gram model available. Build one: python3 "
                        "scripts/build_ngrams.py <corpus-dir> -o "
                        "data/ngrams.json.gz, or migrate it to PostgreSQL "
                        "with scripts/migrate_ngrams_to_pg.py")
        elif self._model is None:
            from khasi_engine import w2v_client
            self._model = w2v_client.load_local()
        if not self._freq:
            from khasi_spell import corpus_freq
            try:
                self._freq = corpus_freq.load()["counts"]
            except FileNotFoundError:
                self._freq = {}

    # ------------------------------------------------------------------
    # Confusion sets
    # ------------------------------------------------------------------

    def _edits1(self, word: str) -> set[str]:
        """Every single edit of *word* — deletions, transpositions, replacements, insertions."""
        splits = [(word[:i], word[i:]) for i in range(len(word) + 1)]
        out: set[str] = set()
        for L, R in splits:
            if R:
                out.add(L + R[1:])                                  # deletion
                if len(R) > 1:
                    out.add(L + R[1] + R[0] + R[2:])                # transposition
                out.update(L + ch + R[1:] for ch in _ALPHABET)      # replacement
            out.update(L + ch + R for ch in _ALPHABET)              # insertion
        out.discard(word)
        return out

    def confusion_set(self, word: str) -> list[str]:
        """
        Real lexicon words one edit from *word*, commonest first.

        Edit-then-lookup rather than scan-and-measure: a few hundred hash
        probes instead of 34,224 weighted-distance computations.
        """
        w = word.lower()
        hit = self._conf.get(w)
        if hit is None:
            db = self.sp.analyser.db
            own = _tokens.corpus_form(w)
            # One candidate per CORPUS spelling, and never the word's own:
            # `ïa` and `ia`, `ka'n` and `kan` are one word to the model.
            # Deduplicating BEFORE the cut matters — spelling twins of common
            # words carry high counts and used to fill the list, only to be
            # discarded later, pushing the real alternatives out of it.
            by_plain: dict[str, str] = {}
            surfaces = db._surface_index

            def preference(x: str, p: str) -> tuple:
                # Which spelling to show for a corpus spelling several share:
                # a real headword first; among headwords the plain one (`ka`,
                # the clitic, not `ká`, another entry); among the rest the
                # marked one, the lexicon's standard (`ïaid`, not `iaid`).
                exact = x in surfaces
                return (not exact, (x != p) if exact else (x == p), x)

            for x in self._edits1(w):
                if not db.is_known(x):
                    continue
                p = _tokens.corpus_form(x)
                if p == own:
                    continue
                prev = by_plain.get(p)
                if prev is None or preference(x, p) < preference(prev, p):
                    by_plain[p] = x
            hit = sorted(by_plain.values(),
                         key=lambda x: (-self._freq.get(_tokens.corpus_form(x), 0), x))
            hit = hit[: self.max_alternatives]
            self._conf[w] = hit
            while len(self._conf) > _CACHE_LIMIT:
                self._conf.popitem(last=False)
        return hit

    # ------------------------------------------------------------------
    # Contextual fit
    # ------------------------------------------------------------------

    def _unit(self, word: str):
        """Cached unit vector. FastText composes one for unseen words too."""
        v = self._vec.get(word)
        if v is None:
            import numpy as np
            try:
                raw = self._model.wv[word]
            except (KeyError, ValueError):
                return None
            n = float(np.linalg.norm(raw))
            v = raw / n if n else None
            self._vec[word] = v
            while len(self._vec) > _CACHE_LIMIT:
                self._vec.popitem(last=False)
        return v

    def _centroid(self, context: list[str]):
        """Mean unit vector of the context, itself normalised."""
        import numpy as np
        vs = [v for v in (self._unit(c) for c in context) if v is not None]
        if len(vs) < self.min_context:
            return None
        c = np.mean(vs, axis=0)
        n = float(np.linalg.norm(c))
        return c / n if n else None

    def _fit(self, word: str, centroid) -> Optional[float]:
        """
        Cosine between the word and the context centroid.

        Cosine-to-mean rather than mean-of-cosines: one dot product per
        candidate instead of one per context word, which is what makes
        scanning a whole document affordable.
        """
        import numpy as np
        v = self._unit(word)
        if v is None or centroid is None:
            return None
        return float(np.dot(v, centroid))

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def check(self, text: str, min_margin: Optional[float] = None) -> list[RealWordFlag]:
        """Flag correctly spelled words that look contextually wrong.

        *min_margin* overrides the detector's default for this call only;
        the detector is shared by every request of the HTTP service, so it
        is never modified here.
        """
        margin = self.min_margin if min_margin is None else float(min_margin)
        self._ensure()
        matches = list(_TOKEN.finditer(text))
        tokens = [(m.group(0), m.start(), m.end()) for m in matches]
        # Two spellings of each word. `words` is the lexicon's, for lookups
        # and confusion sets; `plain` is the corpus's — no ï, ñ or
        # apostrophe — which is the only spelling the n-gram model and the
        # frequency list have ever seen. Scored in the lexicon's spelling,
        # every `ïaid` floored against `iaid` and was "corrected" to it:
        # the detector told writers to drop their diacritics.
        words = [_tokens.canonical(t).lower() for t, _, _ in tokens]
        plain = [_tokens.corpus_form(w) for w in words]
        # Context never crosses a sentence boundary; see context.py.
        sent = _tokens.sentence_index(text, [(m.start(), m.end()) for m in matches])
        flags: list[RealWordFlag] = []

        for i, (raw, start, end) in enumerate(tokens):
            w = words[i]
            # Two characters, not three. Khasi's noun-class clitics — ka
            # (fem), ki (pl), u (masc), i (dim) — are among the commonest
            # real-word confusions in the language, and a three-character
            # floor excludes every one of them. One-character tokens stay
            # out: their confusion sets are enormous and mostly spurious.
            if len(w) < self.min_length:
                continue
            # Only real words are candidates — anything else is an ordinary
            # misspelling and belongs to the existing path. db.is_known(), a
            # hash lookup, not the full gate: a morphologically derived form
            # has no confusion set worth speaking of.
            if not self.sp.analyser.db.is_known(w):
                continue

            same = [j for j in range(max(0, i - self.window),
                                     min(len(words), i + self.window + 1))
                    if j != i and sent[j] == sent[i]]
            context = [plain[j] for j in same if len(plain[j]) >= 3]
            if len(context) < self.min_context:
                continue

            if self.scorer == "ngram":
                left = [plain[j] for j in range(max(0, i - 2), i) if sent[j] == sent[i]]
                right = [plain[j] for j in range(i + 1, min(len(words), i + 3))
                         if sent[j] == sent[i]]
                centroid = None
                base = self._lm.slot_score(plain[i], left, right)
            else:
                centroid = self._centroid(context)
                if centroid is None:
                    continue
                base = self._fit(plain[i], centroid)
                if base is None:
                    continue

            w_freq = self._freq.get(plain[i], 0)
            best: Optional[tuple[float, str, float]] = None
            considered: list[str] = []

            for alt in self.confusion_set(w):
                alt_plain = _tokens.corpus_form(alt)
                # Another spelling of the same word — a diacritic or an
                # apostrophe the corpus cannot show — is not a different
                # word, and the model cannot tell the two apart.
                if alt_plain == plain[i]:
                    continue
                a_freq = self._freq.get(alt_plain, 0)
                # An alternative the corpus never uses cannot be the word
                # the writer meant, and would score at the floor anyway.
                if a_freq < 1:
                    continue
                # Optional commonness rule (see freq_ratio); off for n-grams.
                if self.freq_ratio and a_freq < max(1, w_freq) * self.freq_ratio:
                    continue
                if self.scorer == "ngram":
                    fit = self._lm.slot_score(alt_plain, left, right)
                else:
                    fit = self._fit(alt_plain, centroid)
                    if fit is None:
                        continue
                considered.append(alt)
                gain = fit - base
                if gain >= margin and (best is None or gain > best[0]):
                    best = (gain, alt, fit)

            if best is not None:
                gain, alt, fit = best
                flags.append(RealWordFlag(
                    word=raw, suggestion=_tokens.match_case(raw, alt),
                    start=start, end=end,
                    margin=round(gain, 4),
                    word_fit=round(base, 4), suggestion_fit=round(fit, 4),
                    word_freq=w_freq, suggestion_freq=self._freq.get(_tokens.corpus_form(alt), 0),
                    alternatives=considered[:5],
                ))
        return flags
