"""
realword.py — detect correctly spelled words used in the wrong place.

The spellchecker is blind to these by construction. `check_sentence()`
examines each token independently and skips anything the confidence gate
accepts, so a real Khasi word sitting where a different real Khasi word
belongs passes silently. Kukich (1992) puts real-word errors at a quarter
to a half of all errors in human writing, so this is not a corner case.

Approach — Mays, Damerau and Mercer (1991), with embeddings standing in
for the trigram model Khasi does not yet have:

  1. Consider only tokens the checker ACCEPTS. Anything it rejects is an
     ordinary spelling error and belongs to the existing path.
  2. Build a confusion set: lexicon words one edit away from the token.
     Generated by edit-then-lookup, not by scanning the vocabulary, so it
     costs a few hundred hash lookups rather than 34,224 distance
     computations.
  3. Score how well the token and each alternative fit the surrounding
     words, as mean cosine similarity in the embedding space.
  4. Flag only when an alternative fits substantially better AND is
     substantially commoner in the corpus.

Why embeddings work here when they failed at ranking
----------------------------------------------------
Re-ranking asked the model to separate orthographic near-neighbours
(`lyngdoh` vs `lyngdop`) — precisely what character n-gram composition
cannot do, since such pairs share nearly all their n-grams. It measured
0.875 vs 0.903 and got it backwards. Here the model is asked whether a
word fits its semantic context, which is what distributional vectors are
actually for. The failure mode of one use is the strength of the other.

Precision over recall, deliberately
-----------------------------------
Wrongly "correcting" a word the writer got right is far more damaging to
trust than missing an error. Every threshold below is set conservatively.

MEASURED — two scorers, and the choice matters enormously
---------------------------------------------------------
Evaluated on 150 untouched corpus sentences (false positives) and 80
sentences with a real-word error injected by swapping a word for a
lexicon neighbour (recall).

    scorer      false-pos   recall   at the same operating point
    embedding        0.7%     3.8%
    n-gram           0.7%    33.8%   <- 9x the recall, 96% precision

The embedding scorer never found a usable point: false positives tracked
recall at every threshold, because cosine-to-centroid asks "is this word
roughly on topic" when the question is "does this word belong in this
slot". Margins for genuine errors (0.09-0.23) overlapped almost entirely
with those for correct words (0.11-0.48). It is kept only as
`scorer="embedding"` so the comparison stays reproducible.

The n-gram scorer separates them cleanly:

    margin   false-pos   recall   precision
       3.0       15.3%    58.8%        67%
       5.0        7.3%    56.2%        80%
       7.0        4.7%    52.5%        86%
      10.0        0.7%    33.8%        96%

Clitic confusions were measured separately, because Khasi's noun-class
clitics (ka fem, ki pl, u masc, i dim) are short, extremely frequent and
almost certainly the commonest real-word error in the language. Swapping
ka<->ki in 80 real sentences:

    margin   false-pos   recall
       6.0        4.0%    41.2%
       7.0        2.7%    30.0%
       8.0        0.0%    25.0%   <- shipped default
      10.0        0.0%    12.5%

Defaults sit at the precision end. Wrongly "correcting" a word the writer
got right costs more trust than a missed error is worth. `min_margin=8.0`
gives zero false positives on clitics in this sample; lower it to 6.0 or
7.0 for materially more recall at a few percent false positives.
"""
from __future__ import annotations

import math
import re
import unicodedata
from dataclasses import dataclass, asdict, field
from typing import Any, Iterable, Optional

# Khasi orthographic inventory for single-character edits. c, f, v, x and z
# are excluded — they do not occur in native Khasi words.
_ALPHABET = "abdeghijklmnoprstuwy" + "ïñ" + "áéíóú"

_TOKEN = re.compile(r"[A-Za-zÏïÑñ]+(?:['\-][A-Za-zÏïÑñ]+)*")


@dataclass
class RealWordFlag:
    """A correctly spelled word that may be the wrong word."""

    word: str
    suggestion: str
    start: int
    end: int
    margin: float                    # how much better the alternative fits
    word_fit: float
    suggestion_fit: float
    word_freq: int
    suggestion_freq: int
    alternatives: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class RealWordDetector:
    """
    Contextual detector for real-word errors.

    Parameters
    ----------
    speller :
        A loaded `KhasiSpeller`. Its lexicon supplies the confusion sets and
        its corpus frequencies the commonness prior.
    min_margin :
        How much better an alternative must fit the context before anything
        is flagged. Log units for the n-gram scorer, cosine points for the
        embedding one. Higher is more conservative.
    freq_ratio :
        The alternative must be at least this many times commoner than the
        observed word. Left at 1.0 (no constraint) for the n-gram scorer,
        which already accounts for commonness; it was needed to keep the
        embedding scorer from proposing rare words that sat near the
        context vectors.
    scorer :
        "ngram" (default) or "embedding". See the measurements above.
    min_context :
        Minimum number of usable context words. Below this there is not
        enough signal and the token is skipped.
    """

    def __init__(
        self,
        speller: Any,
        min_margin: float = 8.0,    # log units; see the tables above
        freq_ratio: float = 1.0,    # the LM already encodes commonness
        min_context: int = 2,
        window: int = 6,
        max_alternatives: int = 12,
        min_length: int = 2,
        scorer: str = "ngram",      # "ngram" | "embedding"
    ) -> None:
        self.sp = speller
        self.scorer = scorer
        self._lm = None
        self.min_margin = min_margin
        self.freq_ratio = freq_ratio
        self.min_context = min_context
        self.window = window
        self.max_alternatives = max_alternatives
        self.min_length = min_length
        self._model = None
        self._freq: dict[str, int] = {}
        self._vec: dict[str, Any] = {}      # word -> unit vector, cached
        self._conf: dict[str, list[str]] = {}   # word -> confusion set, cached

    # ------------------------------------------------------------------
    # Lazy resources
    # ------------------------------------------------------------------

    def _ensure(self) -> None:
        if self.scorer == "ngram":
            if self._lm is None:
                # Same backend choice the speller makes — PostgreSQL when it
                # holds the counts, the file otherwise. Built here too so
                # real-word detection does not quietly pull 181 MB of dicts
                # into a process that chose the PG backend to avoid them.
                from khasi_spell.speller import KhasiSpeller
                self._lm = KhasiSpeller._build_lm(None) or None
                if self._lm is None:
                    raise FileNotFoundError("no n-gram model available")
        elif self._model is None:
            from khasi_engine import w2v_client
            self._model = w2v_client.load_local()
        if not self._freq:
            from khasi_spell import corpus_freq
            try:
                self._freq = corpus_freq.load()["counts"]
            except FileNotFoundError:
                self._freq = {}

    # ------------------------------------------------------------------
    # Confusion sets
    # ------------------------------------------------------------------

    def _edits1(self, word: str) -> set[str]:
        """Every single edit of *word* — deletions, transpositions, replacements, insertions."""
        splits = [(word[:i], word[i:]) for i in range(len(word) + 1)]
        out: set[str] = set()
        for L, R in splits:
            if R:
                out.add(L + R[1:])                                  # deletion
                if len(R) > 1:
                    out.add(L + R[1] + R[0] + R[2:])                # transposition
                out.update(L + ch + R[1:] for ch in _ALPHABET)      # replacement
            out.update(L + ch + R for ch in _ALPHABET)              # insertion
        out.discard(word)
        return out

    def confusion_set(self, word: str) -> list[str]:
        """
        Real lexicon words one edit from *word*, commonest first.

        Edit-then-lookup rather than scan-and-measure: a few hundred hash
        probes instead of 34,224 weighted-distance computations.
        """
        w = word.lower()
        hit = self._conf.get(w)
        if hit is None:
            db = self.sp.analyser.db
            hit = [x for x in self._edits1(w) if db.is_known(x)]
            hit.sort(key=lambda x: -self._freq.get(x, 0))
            hit = hit[: self.max_alternatives]
            self._conf[w] = hit
        return hit

    # ------------------------------------------------------------------
    # Contextual fit
    # ------------------------------------------------------------------

    def _unit(self, word: str):
        """Cached unit vector. FastText composes one for unseen words too."""
        v = self._vec.get(word)
        if v is None:
            import numpy as np
            try:
                raw = self._model.wv[word]
            except (KeyError, ValueError):
                return None
            n = float(np.linalg.norm(raw))
            v = raw / n if n else None
            self._vec[word] = v
        return v

    def _centroid(self, context: list[str]):
        """Mean unit vector of the context, itself normalised."""
        import numpy as np
        vs = [v for v in (self._unit(c) for c in context) if v is not None]
        if len(vs) < self.min_context:
            return None
        c = np.mean(vs, axis=0)
        n = float(np.linalg.norm(c))
        return c / n if n else None

    def _fit(self, word: str, centroid) -> Optional[float]:
        """
        Cosine between the word and the context centroid.

        Cosine-to-mean rather than mean-of-cosines: one dot product per
        candidate instead of one per context word, which is what makes
        scanning a whole document affordable.
        """
        import numpy as np
        v = self._unit(word)
        if v is None or centroid is None:
            return None
        return float(np.dot(v, centroid))

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def check(self, text: str) -> list[RealWordFlag]:
        """Flag correctly spelled words that look contextually wrong."""
        self._ensure()
        tokens = [(m.group(0), m.start(), m.end()) for m in _TOKEN.finditer(text)]
        words = [unicodedata.normalize("NFC", t).lower() for t, _, _ in tokens]
        flags: list[RealWordFlag] = []

        for i, (raw, start, end) in enumerate(tokens):
            w = words[i]
            # Two characters, not three. Khasi's noun-class clitics — ka
            # (fem), ki (pl), u (masc), i (dim) — are among the commonest
            # real-word confusions in the language, and a three-character
            # floor excludes every one of them. One-character tokens stay
            # out: their confusion sets are enormous and mostly spurious.
            if len(w) < self.min_length:
                continue
            # Only real words are candidates — anything else is an ordinary
            # misspelling and belongs to the existing path.
            #
            # db.is_known(), not sp.is_correct(): the latter routes unknown
            # tokens through the full gate-3 candidate scan at ~2 s each,
            # which makes scanning a document impossible. A lexicon hit is a
            # hash lookup, and for real-word detection it is the right test
            # anyway — a morphologically derived form has no confusion set
            # worth speaking of.
            if not self.sp.analyser.db.is_known(w):
                continue

            lo = max(0, i - self.window)
            hi = min(len(words), i + self.window + 1)
            context = [words[j] for j in range(lo, hi) if j != i and len(words[j]) >= 3]
            if len(context) < self.min_context:
                continue

            if self.scorer == "ngram":
                left = [words[j] for j in range(max(0, i - 2), i)]
                right = words[i + 1:i + 3]
                centroid = None
                base = self._lm.slot_score(w, left, right)
            else:
                centroid = self._centroid(context)
                if centroid is None:
                    continue
                base = self._fit(w, centroid)
                if base is None:
                    continue

            w_freq = self._freq.get(w, 0)
            best: Optional[tuple[float, str, float]] = None
            considered: list[str] = []

            for alt in self.confusion_set(w):
                a_freq = self._freq.get(alt, 0)
                # The alternative must be materially commoner, or we are just
                # swapping one plausible word for another on a noisy signal.
                if a_freq < max(1, w_freq) * self.freq_ratio:
                    continue
                if self.scorer == "ngram":
                    fit = self._lm.slot_score(alt, left, right)
                else:
                    fit = self._fit(alt, centroid)
                    if fit is None:
                        continue
                considered.append(alt)
                margin = fit - base
                if margin >= self.min_margin and (best is None or margin > best[0]):
                    best = (margin, alt, fit)

            if best is not None:
                margin, alt, fit = best
                flags.append(RealWordFlag(
                    word=raw, suggestion=alt, start=start, end=end,
                    margin=round(margin, 4),
                    word_fit=round(base, 4), suggestion_fit=round(fit, 4),
                    word_freq=w_freq, suggestion_freq=self._freq.get(alt, 0),
                    alternatives=considered[:5],
                ))
        return flags
