#!/usr/bin/env python3
"""
fix_ain_coda_tilde.py — write the tilde on a CODA n: `ain` -> `aiñ`.

Third and last pass in the diaeresis/tilde family, after
`fix_ain_diaeresis.py` (aïñ -> aiñ) and `fix_vin_diaeresis.py`
(eïñ/oïñ/uïñ -> eiñ/oiñ/uiñ). Two maintainer rules are applied here:

RULE 1 — `ï` and `ñ` never sit next to each other, so a surviving `ïñ`
         becomes `iñ`. The vowel-preceded cases were done by
         `fix_vin_diaeresis.py`; the one left is `leh rymmolïñ`, where a
         CONSONANT precedes, which that pass deliberately skipped.
         NOTE: this fixes the diaeresis only. `rymmolïñ` is probably also
         scan damage (`rymmoïñ` exists, so `o` was likely read as `ol`);
         that is a separate reading of the OCR and is NOT done here.

RULE 2 — a word-final / syllable-final `ain` is spelled `aiñ`. The tilde
         goes on the nasal when the nasal is a CODA. Scope matters, and is
         decided by what FOLLOWS the `ain`:

           jain-pun, dain, kyllain    boundary   -> coda      APPLY
           jainkhor, daindong         consonant  -> coda      APPLY
           bainong, daini, sainar     vowel      -> onset     SKIP
           ainguh, laingut, baingon   `g`        -> `ng` onset SKIP

         So: replace `ain` unless a vowel (a e i o u y and accented forms,
         plus ï) or `g` follows.

Evidence, gathered as the earlier passes gathered theirs — 31 surfaces are
recorded BOTH ways, which is error and not variant:

    dain/daiñ    jain/jaiñ      kain/kaiñ      lain/laiñ     main/maiñ
    kyllain/kyllaiñ    khyrwain/khyrwaiñ      mynsain/mynsaiñ
    jarain/jaraiñ      ksain/ksaiñ            sympain/sympaiñ

Counts before this pass: 615 surfaces already spell it `aiñ`, 115 have a
token-final `ain`, 24 more have `ain` + consonant.

Excluded by entry_id
--------------------
kh_DB_008212 `balei phi ïaid jaw-jaw ha u slap in the rain` — the tail of
this surface is English ("in the rain"), captured from the source
dictionary's own example text. Applying the rule would produce "raiñ".
The entry's Khasi portion needs no change, so the whole record is skipped.

    python3 scripts/fix_ain_coda_tilde.py --dry-run
    python3 scripts/fix_ain_coda_tilde.py
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import shutil
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "khasi_db.json"

# `y`/`ý` count as vowels in Khasi (the y-nucleus ruling, roadmap item 1).
VOWELS = "aeiouáéíóúyýï"
AIN_CODA = re.compile(f"ain(?![{VOWELS}g])")

SKIP_ENTRY_IDS = {"kh_DB_008212"}   # English tail — see module docstring

# ALLOWLIST of the fields that carry Khasi orthography.
#
# The two earlier passes walked every string in the entry, justified by
# "`aïñ` cannot occur in an English gloss". True of `aïñ`, and emphatically
# FALSE of `ain`: remain, contain, plain, train, certain, explain, again.
# A blanket walk here rewrote 432 `remain`, 382 `contain` and 164 `plain`.
#
# A denylist of English keys was tried next and was ALSO wrong: the English
# is not only in glosses. It hides in provenance —
# `source.prefix_decomposition_v2_note` alone holds 352 matches, plus
# `source.note`, `source.source_entry` and `meta.changelog`.
#
# So this pass names the Khasi fields instead. Anything not listed is never
# touched. Any future pass over a sequence that is also an English string
# must do the same.
KHASI_PATHS = (
    ("form", "surface"),
    ("form", "normalized"),
    ("form", "variants"),
    ("lemma", "root"),
    ("lemma", "root_id"),
    ("morphology", "canonical"),
    ("morphology", "structure"),          # [{type, form:{raw}}] — Khasi only
    ("phonology", "surface"),
    ("phonology", "derived", "syllables"),
    ("lexical_relations", "related"),
    ("lexical_relations", "better_forms"),
)
# phonology.ipa is deliberately absent: it is regenerated by
# khasi_engine/g2p.py, not string-edited.


def fix(text: str) -> str:
    text = text.replace("ïñ", "iñ")          # RULE 1
    return AIN_CODA.sub("aiñ", text)         # RULE 2


def _fix_in(node, key) -> int:
    """Apply `fix` to every string under node[key], recursively."""
    value = node[key]
    if isinstance(value, str):
        new = fix(value)
        if new != value:
            node[key] = new
            return 1
        return 0
    changed = 0
    if isinstance(value, dict):
        for k in list(value):
            changed += _fix_in(value, k)
    elif isinstance(value, list):
        for i in range(len(value)):
            changed += _fix_in(value, i)
    return changed


def walk(entries) -> int:
    """Rewrite only the allowlisted Khasi fields of each entry."""
    changed = 0
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        for path in KHASI_PATHS:
            node = entry
            for step in path[:-1]:
                node = node.get(step) if isinstance(node, dict) else None
                if not isinstance(node, dict):
                    node = None
                    break
            if node is None or path[-1] not in node:
                continue
            changed += _fix_in(node, path[-1])
    return changed


def main() -> int:
    ap = argparse.ArgumentParser(description="ïñ -> iñ, and coda ain -> aiñ")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--db", type=Path, default=DB)
    args = ap.parse_args()

    data = json.loads(args.db.read_text(encoding="utf-8"))
    _before_blob = json.dumps(data, ensure_ascii=False)
    before_counts = {w: _before_blob.count(w) for w in
                     ("remaiñ", "contaiñ", "certaiñ", "explaiñ", "chaiñ",
                      "maintaiñ", "obtaiñ", "agaiñ", "attaiñ", "complaiñ")}

    def surface(e):
        return (e.get("form") or {}).get("surface") or ""

    targets = [e for e in data["lexicon"]
               if e.get("entry_id") not in SKIP_ENTRY_IDS
               and fix(surface(e)) != surface(e)]
    print(f"  surfaces to change: {len(targets)}")
    skipped = [e for e in data["lexicon"]
               if e.get("entry_id") in SKIP_ENTRY_IDS and fix(surface(e)) != surface(e)]
    for e in skipped:
        print(f"  SKIPPED (English tail): {surface(e)!r}")

    if args.dry_run:
        for e in targets[:20]:
            print(f"      {surface(e)}  ->  {fix(surface(e))}")
        print("\n  --dry-run: nothing written")
        return 0

    backup = args.db.with_name(
        f"{args.db.name}.bak.{datetime.now():%Y%m%d_%H%M%S}")
    shutil.copy2(args.db, backup)
    print(f"  backup -> {backup.name}")

    # Hold the excluded entries out of the walk, then put them back.
    held = [e for e in data["lexicon"] if e.get("entry_id") in SKIP_ENTRY_IDS]
    data["lexicon"] = [e for e in data["lexicon"]
                       if e.get("entry_id") not in SKIP_ENTRY_IDS]
    # The lexicon only. `quarantine` is the audit trail of what was
    # withdrawn and must keep the spelling it had when it was withdrawn —
    # and those records are precisely the English/OCR junk whose "surfaces"
    # are English text ("again", …), so rewriting them corrupts the record.
    changed = walk(data["lexicon"])
    data["lexicon"].extend(held)

    spec = importlib.util.spec_from_file_location(
        "fix_ia", Path(__file__).with_name("fix_ia_diaeresis.py"))
    fix_ia = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fix_ia)
    merge = fix_ia.dedupe(data)
    print(f"  deduped: {merge['merged']} entries merged across "
          f"{merge['surfaces']} surfaces, {merge['glosses_added']} glosses kept")

    # Guard: no English word may have been rewritten. Compares against the
    # count BEFORE the pass rather than testing for presence, because some
    # of these sequences legitimately occur inside Khasi words — `kyntraiñ`
    # contains "traiñ", and `plaiñ-plaiñ` is a real reduplication. Only an
    # INCREASE means this pass damaged English text.
    ENGLISH_PROBES = ("remaiñ", "contaiñ", "certaiñ", "explaiñ", "chaiñ",
                      "maintaiñ", "obtaiñ", "agaiñ", "attaiñ", "complaiñ")
    after_blob = json.dumps(data, ensure_ascii=False)
    damaged = {w: (before_counts[w], after_blob.count(w))
               for w in ENGLISH_PROBES
               if after_blob.count(w) > before_counts[w]}
    if damaged:
        raise SystemExit(
            f"ABORT: English text was rewritten (before -> after): {damaged}. "
            f"Nothing written; the file on disk is untouched.")

    stamp = datetime.now().strftime("%Y-%m-%d")
    data.setdefault("meta", {})["ain_coda_tilde_fix"] = {
        "date": stamp, "strings_changed": changed,
        "surfaces_changed": len(targets), "merged": merge["merged"],
        "skipped_entry_ids": sorted(SKIP_ENTRY_IDS),
    }
    args.db.write_text(json.dumps(data, ensure_ascii=False, indent=1),
                       encoding="utf-8")
    print(f"  strings changed: {changed}")
    print(f"  lexicon entries: {len(data['lexicon'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
